# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dokerfile                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vgongora <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/11 16:16:34 by vgongora          #+#    #+#              #
#    Updated: 2019/10/11 17:23:07 by vgongora         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# -ONBUILD --> instruction adds to the image a trigger instruction to be executed at a later time, when the image is used as the base for another build. The trigger will be executed in the context of the downstream build,  as if it had been inserted immediately after the FROM  instruction in the downstream Dockerfile.
#  **any build instruction can be registered as a trigger.

##Steps:
# run container (linux  I believe)
# install ruby (research)
# create rails app
# run app and access it (localhost:3000)

FROM ruby



EXPOSE 3000
